name = "LifeGame"
uuid = "699e2175-2ccb-4b83-83e3-62ae42f966df"
authors = ["Michael Greenburg <michaeljgreenburg@gmail.com>"]
version = "0.1.0"

[deps]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
